version: "3.8"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - target: 80
        published: 80
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
  front-end:
    container_name: front-end
    image: chr1ss4av/front-end:latest
    build: ./front-end
    environment:
      PASSWORD: ${MYSQL_ROOT_PASSWORD}
  special-api:
    container_name: special-api
    image: chr1ss4v/special-api:latest
    build: ./special-api
    deploy:
      replicas: 3]
  traits-api:
    container_name: traits-api
    image: chr1ss4v/traits-api:latest
    build: ./traits-api
    deploy:
      replicas: 3
  stats-api:
    container_name: stats-api
    image: chr1ss4v/stats-api:latest
    build: ./stats-api
    deploy:
      replicas: 3
  tags-api:
    container_name: tags-api
    image: chr1ss4v/tags-api:latest
    build: ./tags-api
    deploy:
      replicas: 3  