- hosts: devvm
  become: true
  roles:
  - python
  - docker
  - docker-compose
  tasks:
  - name: create git dir
    file:
      state: directory
      path: /home/chris_sav/DevOps-Core-Practical-Project
  - name: clone repo
    git:
      repo: https://github.com/Christian-Sav/DevOps-Core-Practical-Project.git
      dest: /home/chris_sav/DevOps-Core-Practical-Project
      clone: yes
  vars:
    docker_user: chr1ss4v

- hosts: ciserver
  become: true
  roles:
  - python
  - docker
  - docker-compose
  - jenkins
  vars:
    docker_user: jenkins

- hosts: swarmmanagers
  become: true
  roles:
  - docker
  - swarm-manager
  tasks:
  - name: add ansible user to docker group
    user:
      name: notascene
      groups: docker
      append: yes
  vars:
    docker_user: jenkins

- hosts: swarmworkers
  become: true
  roles:
  - docker
  - swarm-worker
  vars:
    docker_user: chr1ss4v